#!/bin/bash
#===============================================================================
# DataViz Studio - Auto-Deployment Script
# Industry-standard deployment automation for development and production
#
# Usage:
#   ./deploy.sh              # Auto-detect environment from APP_ENV
#   ./deploy.sh development  # Force development mode
#   ./deploy.sh production   # Force production mode
#   ./deploy.sh --check      # Check current configuration
#   ./deploy.sh --help       # Show help
#
# Environment Variables:
#   APP_ENV          - Environment (development|production), default: development
#   REDIS_REPLICAS   - Number of Redis replicas for production (default: 3)
#   CELERY_WORKERS   - Number of Celery workers (default: 2 dev, 4 prod)
#   MONGO_REPLICAS   - Number of MongoDB replicas for production (default: 3)
#===============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Default configuration
APP_ENV="${APP_ENV:-development}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="${SCRIPT_DIR}/backend"
FRONTEND_DIR="${SCRIPT_DIR}/frontend"
CONFIG_DIR="${SCRIPT_DIR}/config"
LOG_DIR="/var/log/dataviz"

# Production defaults
PROD_CELERY_WORKERS="${CELERY_WORKERS:-4}"
PROD_REDIS_REPLICAS="${REDIS_REPLICAS:-3}"
PROD_MONGO_REPLICAS="${MONGO_REPLICAS:-3}"

# Development defaults
DEV_CELERY_WORKERS="${CELERY_WORKERS:-2}"

#===============================================================================
# Utility Functions
#===============================================================================

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_section() {
    echo ""
    echo -e "${CYAN}═══════════════════════════════════════════════════════════════════${NC}"
    echo -e "${CYAN}  $1${NC}"
    echo -e "${CYAN}═══════════════════════════════════════════════════════════════════${NC}"
}

check_command() {
    if command -v "$1" &> /dev/null; then
        return 0
    else
        return 1
    fi
}

wait_for_service() {
    local host=$1
    local port=$2
    local max_attempts=${3:-30}
    local attempt=0

    while [ $attempt -lt $max_attempts ]; do
        if nc -z "$host" "$port" 2>/dev/null; then
            return 0
        fi
        sleep 1
        ((attempt++))
    done
    return 1
}

#===============================================================================
# Environment Detection
#===============================================================================

detect_environment() {
    # Override from command line if provided
    if [ -n "$1" ] && [ "$1" != "--check" ] && [ "$1" != "--help" ]; then
        APP_ENV="$1"
    fi

    # Validate environment
    if [ "$APP_ENV" != "development" ] && [ "$APP_ENV" != "production" ]; then
        log_error "Invalid environment: $APP_ENV"
        log_info "Valid environments: development, production"
        exit 1
    fi

    log_info "Environment detected: ${CYAN}${APP_ENV}${NC}"
}

#===============================================================================
# Configuration Generators
#===============================================================================

generate_env_file() {
    log_section "Generating Environment Configuration"
    
    local backend_env="${BACKEND_DIR}/.env"
    
    # Backup existing env file
    if [ -f "$backend_env" ]; then
        cp "$backend_env" "${backend_env}.bak"
        log_info "Backed up existing .env to .env.bak"
    fi

    if [ "$APP_ENV" == "production" ]; then
        # Production configuration
        cat > "$backend_env" << 'EOF'
# DataViz Studio - Production Configuration
# Auto-generated by deploy.sh

# MongoDB Configuration (Replica Set)
MONGO_URL="${MONGO_URL:-mongodb://localhost:27017}"
DB_NAME="${DB_NAME:-dataviz_studio}"
MONGO_REPLICA_SET="${MONGO_REPLICA_SET:-dataviz-rs}"
MONGO_READ_PREFERENCE="${MONGO_READ_PREFERENCE:-secondaryPreferred}"
MONGO_WRITE_CONCERN="${MONGO_WRITE_CONCERN:-majority}"
MONGO_MAX_POOL_SIZE=100
MONGO_MIN_POOL_SIZE=10

# Redis Configuration (Cluster)
REDIS_URL="${REDIS_URL:-redis://localhost:6379/0}"
REDIS_CLUSTER_MODE=true
REDIS_MAX_CONNECTIONS=50
CACHE_ENABLED=true

# Celery Configuration
CELERY_BROKER_URL="${CELERY_BROKER_URL:-redis://localhost:6379/0}"
CELERY_RESULT_BACKEND="${CELERY_RESULT_BACKEND:-redis://localhost:6379/0}"
CELERY_WORKER_CONCURRENCY=4
CELERY_PREFETCH_MULTIPLIER=4

# Security
JWT_SECRET="${JWT_SECRET:-$(openssl rand -hex 32)}"
CORS_ORIGINS="${CORS_ORIGINS:-https://your-domain.com}"
SECURE_COOKIES=true
RATE_LIMIT_ENABLED=true

# Logging
LOG_LEVEL=INFO
LOG_FORMAT=json

# Performance
API_PAGINATION_DEFAULT=50
API_PAGINATION_MAX=500
QUERY_TIMEOUT_SECONDS=30
EOF
        log_info "Generated production .env configuration"
    else
        # Development configuration - preserve existing keys
        if [ ! -f "$backend_env" ]; then
            cat > "$backend_env" << 'EOF'
# DataViz Studio - Development Configuration
# Auto-generated by deploy.sh

# MongoDB Configuration
MONGO_URL=mongodb://localhost:27017
DB_NAME=test_database

# Redis Configuration
REDIS_URL=redis://localhost:6379/0
CACHE_ENABLED=true

# Celery Configuration
CELERY_BROKER_URL=redis://localhost:6379/0
CELERY_RESULT_BACKEND=redis://localhost:6379/0

# Security (Development)
JWT_SECRET=dev-secret-change-in-production
CORS_ORIGINS=*

# Logging
LOG_LEVEL=DEBUG
LOG_FORMAT=console

# Performance
API_PAGINATION_DEFAULT=20
API_PAGINATION_MAX=100
QUERY_TIMEOUT_SECONDS=60
EOF
            log_info "Generated development .env configuration"
        else
            log_info "Keeping existing development .env configuration"
        fi
    fi
}

generate_supervisor_config() {
    log_section "Generating Supervisor Configuration"

    local celery_workers
    local redis_config
    
    if [ "$APP_ENV" == "production" ]; then
        celery_workers=$PROD_CELERY_WORKERS
        redis_config="redis-server --cluster-enabled yes --maxmemory 1gb --maxmemory-policy allkeys-lru"
    else
        celery_workers=$DEV_CELERY_WORKERS
        redis_config="redis-server --port 6379 --maxmemory 256mb --maxmemory-policy allkeys-lru"
    fi

    # Create Celery Supervisor Config
    cat > "${SCRIPT_DIR}/supervisor_celery.conf" << EOF
; DataViz Studio - Celery Worker Configuration
; Environment: ${APP_ENV}
; Generated by deploy.sh

[program:celery_worker]
command=celery -A utils.tasks worker --loglevel=info --concurrency=4 --queues=celery,high_priority,low_priority
directory=${BACKEND_DIR}
user=root
numprocs=${celery_workers}
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=${LOG_DIR}/celery_worker_%(process_num)02d.log
stderr_logfile=${LOG_DIR}/celery_worker_%(process_num)02d_err.log
autostart=true
autorestart=true
startsecs=10
stopwaitsecs=600
stopasgroup=true
killasgroup=true
priority=998
environment=PYTHONPATH="${BACKEND_DIR}"

[program:celery_beat]
command=celery -A utils.tasks beat --loglevel=info
directory=${BACKEND_DIR}
user=root
numprocs=1
stdout_logfile=${LOG_DIR}/celery_beat.log
stderr_logfile=${LOG_DIR}/celery_beat_err.log
autostart=true
autorestart=true
startsecs=10
priority=999
environment=PYTHONPATH="${BACKEND_DIR}"

[group:celery]
programs=celery_worker,celery_beat
EOF

    log_success "Generated supervisor_celery.conf with ${celery_workers} workers"

    # Create Redis Supervisor Config (if Redis server is available)
    if check_command redis-server; then
        cat > "${SCRIPT_DIR}/supervisor_redis.conf" << EOF
; DataViz Studio - Redis Configuration
; Environment: ${APP_ENV}
; Generated by deploy.sh

[program:redis]
command=${redis_config}
user=root
autostart=true
autorestart=true
stdout_logfile=${LOG_DIR}/redis.log
stderr_logfile=${LOG_DIR}/redis_err.log
priority=100
EOF
        log_success "Generated supervisor_redis.conf"
    else
        log_warning "Redis server not installed, skipping Redis supervisor config"
    fi
}

generate_mongodb_config() {
    log_section "Generating MongoDB Configuration"

    mkdir -p "${CONFIG_DIR}"

    if [ "$APP_ENV" == "production" ]; then
        # Production MongoDB Config (Replica Set ready)
        cat > "${CONFIG_DIR}/mongod.conf" << EOF
# DataViz Studio - MongoDB Production Configuration
# Environment: ${APP_ENV}
# Generated by deploy.sh

storage:
  dbPath: /var/lib/mongodb
  journal:
    enabled: true
  wiredTiger:
    engineConfig:
      cacheSizeGB: 4
    collectionConfig:
      blockCompressor: snappy

systemLog:
  destination: file
  logAppend: true
  path: ${LOG_DIR}/mongodb.log

net:
  port: 27017
  bindIp: 0.0.0.0

replication:
  replSetName: dataviz-rs

security:
  authorization: enabled

operationProfiling:
  slowOpThresholdMs: 100
  mode: slowOp
EOF
        log_success "Generated production MongoDB configuration (replica set enabled)"
        
        # Generate replica set initialization script
        cat > "${CONFIG_DIR}/init_replica_set.js" << 'EOF'
// DataViz Studio - MongoDB Replica Set Initialization
// Run this on the primary node after all nodes are running

rs.initiate({
  _id: "dataviz-rs",
  members: [
    { _id: 0, host: "mongo-primary:27017", priority: 2 },
    { _id: 1, host: "mongo-secondary-1:27017", priority: 1 },
    { _id: 2, host: "mongo-secondary-2:27017", priority: 1 }
  ]
});

// Wait for replica set to initialize
sleep(5000);

// Check status
rs.status();
EOF
        log_info "Generated replica set initialization script: ${CONFIG_DIR}/init_replica_set.js"

    else
        # Development MongoDB Config (Single instance)
        cat > "${CONFIG_DIR}/mongod.conf" << EOF
# DataViz Studio - MongoDB Development Configuration
# Environment: ${APP_ENV}
# Generated by deploy.sh

storage:
  dbPath: /var/lib/mongodb
  journal:
    enabled: true

systemLog:
  destination: file
  logAppend: true
  path: ${LOG_DIR}/mongodb.log

net:
  port: 27017
  bindIp: 127.0.0.1
EOF
        log_success "Generated development MongoDB configuration"
    fi
}

#===============================================================================
# Database Setup
#===============================================================================

setup_database_indexes() {
    log_section "Setting Up Database Indexes"

    # Python script to create indexes
    cat > /tmp/setup_indexes.py << 'EOF'
import asyncio
import os
import sys
sys.path.insert(0, os.environ.get('BACKEND_DIR', '/app/backend'))

from motor.motor_asyncio import AsyncIOMotorClient
from dotenv import load_dotenv

load_dotenv()

async def create_indexes():
    mongo_url = os.environ.get('MONGO_URL', 'mongodb://localhost:27017')
    db_name = os.environ.get('DB_NAME', 'test_database')
    
    client = AsyncIOMotorClient(mongo_url)
    db = client[db_name]
    
    indexes = [
        ("users", [("email", 1)], {"unique": True}),
        ("users", [("id", 1)], {}),
        ("dashboards", [("id", 1)], {}),
        ("dashboards", [("user_id", 1)], {}),
        ("dashboards", [("org_id", 1)], {}),
        ("datasets", [("id", 1)], {}),
        ("datasets", [("user_id", 1)], {}),
        ("dataset_data", [("dataset_id", 1)], {}),
        ("dataset_data", [("dataset_id", 1), ("created_at", -1)], {}),
        ("widgets", [("dashboard_id", 1)], {}),
        ("templates", [("id", 1)], {}),
        ("templates", [("user_id", 1)], {}),
        ("data_sources", [("id", 1)], {}),
        ("data_sources", [("user_id", 1)], {}),
    ]
    
    for collection, keys, options in indexes:
        try:
            await db[collection].create_index(keys, **options)
            print(f"  Created index on {collection}: {keys}")
        except Exception as e:
            print(f"  Index exists or error on {collection}: {e}")
    
    client.close()
    print("Database indexes setup complete!")

if __name__ == "__main__":
    asyncio.run(create_indexes())
EOF

    export BACKEND_DIR="${BACKEND_DIR}"
    python3 /tmp/setup_indexes.py && log_success "Database indexes created" || log_warning "Some indexes may already exist"
    rm /tmp/setup_indexes.py
}

#===============================================================================
# Service Health Checks
#===============================================================================

check_services() {
    log_section "Checking Service Health"

    local all_healthy=true

    # Check MongoDB
    if check_command mongosh || check_command mongo; then
        if mongosh --quiet --eval "db.adminCommand('ping')" 2>/dev/null || mongo --quiet --eval "db.adminCommand('ping')" 2>/dev/null; then
            log_success "MongoDB: Running"
        else
            log_warning "MongoDB: Not responding"
            all_healthy=false
        fi
    else
        log_warning "MongoDB client not installed, checking port..."
        if wait_for_service localhost 27017 5; then
            log_success "MongoDB: Port 27017 open"
        else
            log_warning "MongoDB: Port 27017 not responding"
            all_healthy=false
        fi
    fi

    # Check Redis
    if check_command redis-cli; then
        if redis-cli ping 2>/dev/null | grep -q "PONG"; then
            log_success "Redis: Running"
        else
            log_warning "Redis: Not responding (caching will be disabled)"
        fi
    else
        log_warning "Redis client not installed, checking port..."
        if wait_for_service localhost 6379 5; then
            log_success "Redis: Port 6379 open"
        else
            log_warning "Redis: Not running (caching will be disabled)"
        fi
    fi

    # Check Backend API
    local backend_url="http://localhost:8001"
    if curl -s "${backend_url}/api/health" 2>/dev/null | grep -q "healthy"; then
        log_success "Backend API: Running"
    else
        log_warning "Backend API: Not responding"
        all_healthy=false
    fi

    # Check Frontend
    if curl -s "http://localhost:3000" 2>/dev/null > /dev/null; then
        log_success "Frontend: Running"
    else
        log_warning "Frontend: Not responding"
        all_healthy=false
    fi

    # Check Celery Workers
    if check_command celery; then
        local celery_status=$(celery -A utils.tasks inspect ping 2>/dev/null || echo "")
        if echo "$celery_status" | grep -q "pong"; then
            log_success "Celery Workers: Running"
        else
            log_warning "Celery Workers: Not responding"
        fi
    fi

    echo ""
    if [ "$all_healthy" = true ]; then
        log_success "All core services are healthy!"
    else
        log_warning "Some services need attention"
    fi
}

#===============================================================================
# Install Dependencies
#===============================================================================

install_dependencies() {
    log_section "Installing Dependencies"

    # Backend dependencies
    if [ -f "${BACKEND_DIR}/requirements.txt" ]; then
        log_info "Installing Python dependencies..."
        pip install -r "${BACKEND_DIR}/requirements.txt" -q && log_success "Python dependencies installed" || log_error "Failed to install Python dependencies"
    fi

    # Frontend dependencies
    if [ -f "${FRONTEND_DIR}/package.json" ]; then
        log_info "Installing Node.js dependencies..."
        cd "${FRONTEND_DIR}"
        yarn install --silent && log_success "Node.js dependencies installed" || log_error "Failed to install Node.js dependencies"
        cd "${SCRIPT_DIR}"
    fi
}

#===============================================================================
# Start/Restart Services
#===============================================================================

start_services() {
    log_section "Starting Services"

    # Create log directory
    mkdir -p "${LOG_DIR}"

    # Restart supervisor-managed services
    if check_command supervisorctl; then
        log_info "Restarting services via Supervisor..."
        sudo supervisorctl reread 2>/dev/null || true
        sudo supervisorctl update 2>/dev/null || true
        sudo supervisorctl restart backend 2>/dev/null && log_success "Backend restarted" || log_warning "Backend restart failed"
        sudo supervisorctl restart frontend 2>/dev/null && log_success "Frontend restarted" || log_warning "Frontend restart failed"
        
        # Restart Celery workers if config exists
        if [ -f "${SCRIPT_DIR}/supervisor_celery.conf" ]; then
            sudo supervisorctl restart celery_worker:* 2>/dev/null && log_success "Celery workers restarted" || log_warning "Celery worker restart failed"
            sudo supervisorctl restart celery_beat 2>/dev/null && log_success "Celery beat restarted" || log_warning "Celery beat restart failed"
        fi
    else
        log_warning "Supervisor not available, services must be started manually"
    fi

    # Wait for services to start
    log_info "Waiting for services to initialize..."
    sleep 5
}

#===============================================================================
# Production-Specific Setup
#===============================================================================

setup_production() {
    log_section "Production-Specific Setup"

    # Security checks
    log_info "Running security checks..."
    
    # Check for default secrets
    if grep -q "dev-secret\|change-me\|your-secret" "${BACKEND_DIR}/.env" 2>/dev/null; then
        log_error "SECURITY WARNING: Default secrets detected in .env file!"
        log_info "Please update JWT_SECRET and other sensitive values before deploying to production"
    else
        log_success "No default secrets detected"
    fi

    # Check CORS configuration
    if grep -q 'CORS_ORIGINS="\*"' "${BACKEND_DIR}/.env" 2>/dev/null; then
        log_warning "CORS is set to allow all origins. Update CORS_ORIGINS for production"
    fi

    # Generate deployment checklist
    cat > "${SCRIPT_DIR}/PRODUCTION_CHECKLIST.md" << 'EOF'
# Production Deployment Checklist

## Pre-Deployment

- [ ] Update JWT_SECRET to a secure random value
- [ ] Configure CORS_ORIGINS with your domain(s)
- [ ] Set up SSL/TLS certificates
- [ ] Configure MongoDB replica set
- [ ] Set up Redis cluster
- [ ] Configure backup schedule
- [ ] Set up monitoring (Prometheus, Grafana, etc.)
- [ ] Configure log aggregation
- [ ] Set up alerting

## Infrastructure

- [ ] MongoDB replica set initialized (run config/init_replica_set.js)
- [ ] Redis cluster configured
- [ ] Load balancer configured
- [ ] CDN configured for static assets
- [ ] DNS configured

## Security

- [ ] Firewall rules configured
- [ ] Rate limiting enabled
- [ ] DDoS protection enabled
- [ ] Security headers configured
- [ ] Input validation enabled

## Monitoring

- [ ] Application metrics exported
- [ ] Database metrics monitored
- [ ] Error tracking configured
- [ ] Performance monitoring enabled
- [ ] Uptime monitoring configured

## Backup & Recovery

- [ ] Database backup schedule configured
- [ ] Backup restore tested
- [ ] Disaster recovery plan documented
EOF
    log_success "Generated PRODUCTION_CHECKLIST.md"
}

#===============================================================================
# Status Report
#===============================================================================

show_status() {
    log_section "Deployment Status Report"

    echo ""
    echo -e "${CYAN}Environment:${NC} ${APP_ENV}"
    echo ""

    # Show configuration
    echo -e "${CYAN}Configuration:${NC}"
    if [ "$APP_ENV" == "production" ]; then
        echo "  Celery Workers: ${PROD_CELERY_WORKERS}"
        echo "  Redis Replicas: ${PROD_REDIS_REPLICAS} (cluster mode)"
        echo "  MongoDB Replicas: ${PROD_MONGO_REPLICAS} (replica set)"
        echo "  Cache: Enabled"
        echo "  Rate Limiting: Enabled"
    else
        echo "  Celery Workers: ${DEV_CELERY_WORKERS}"
        echo "  Redis: Single instance"
        echo "  MongoDB: Single instance"
        echo "  Cache: Enabled (graceful degradation)"
    fi

    echo ""
    echo -e "${CYAN}Generated Files:${NC}"
    [ -f "${BACKEND_DIR}/.env" ] && echo "  - backend/.env"
    [ -f "${SCRIPT_DIR}/supervisor_celery.conf" ] && echo "  - supervisor_celery.conf"
    [ -f "${CONFIG_DIR}/mongod.conf" ] && echo "  - config/mongod.conf"
    [ -f "${CONFIG_DIR}/init_replica_set.js" ] && echo "  - config/init_replica_set.js"
    [ -f "${SCRIPT_DIR}/PRODUCTION_CHECKLIST.md" ] && echo "  - PRODUCTION_CHECKLIST.md"

    echo ""
    echo -e "${CYAN}Documentation:${NC}"
    [ -f "${BACKEND_DIR}/docs/INFRASTRUCTURE.md" ] && echo "  - backend/docs/INFRASTRUCTURE.md"

    echo ""
}

#===============================================================================
# Help
#===============================================================================

show_help() {
    echo "DataViz Studio - Auto-Deployment Script"
    echo ""
    echo "Usage:"
    echo "  ./deploy.sh              Auto-detect environment from APP_ENV"
    echo "  ./deploy.sh development  Deploy for development"
    echo "  ./deploy.sh production   Deploy for production"
    echo "  ./deploy.sh --check      Check current configuration and service status"
    echo "  ./deploy.sh --help       Show this help message"
    echo ""
    echo "Environment Variables:"
    echo "  APP_ENV          Environment (development|production)"
    echo "  CELERY_WORKERS   Number of Celery workers"
    echo "  REDIS_REPLICAS   Number of Redis replicas (production)"
    echo "  MONGO_REPLICAS   Number of MongoDB replicas (production)"
    echo ""
    echo "Examples:"
    echo "  APP_ENV=production ./deploy.sh"
    echo "  CELERY_WORKERS=8 ./deploy.sh production"
    echo ""
}

#===============================================================================
# Main Execution
#===============================================================================

main() {
    # Handle special flags
    case "$1" in
        --help|-h)
            show_help
            exit 0
            ;;
        --check)
            log_section "Configuration Check"
            detect_environment
            check_services
            show_status
            exit 0
            ;;
    esac

    log_section "DataViz Studio Deployment"
    log_info "Starting deployment script..."

    # Detect and set environment
    detect_environment "$1"

    # Generate configurations
    generate_env_file
    generate_supervisor_config
    generate_mongodb_config

    # Setup database
    setup_database_indexes

    # Production-specific setup
    if [ "$APP_ENV" == "production" ]; then
        setup_production
    fi

    # Start services
    start_services

    # Health check
    check_services

    # Show status
    show_status

    log_section "Deployment Complete"
    
    if [ "$APP_ENV" == "production" ]; then
        log_warning "Review PRODUCTION_CHECKLIST.md before going live!"
    fi
    
    log_success "DataViz Studio is ready for ${APP_ENV}!"
}

# Run main function
main "$@"
